# Start Check Only deploy source code to all CIBUILD sandboxes once feature has been merged to main branch 
name: Validate Salesforce Sandboxes

on:
# All pushes to main branch
  push:
     branches:
      - main

  # Allows manual run from the Actions tab once this workflow is in default branch
  workflow_dispatch:

# Cancel any subsequent runs of the same branch as they will need to be redeployed with newer config
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  # Performs a Check Only deployment against each CIBUILD salesforce sandbox
  validate-salesforce-sandbox:
    name: Validate Salesforce Sandbox
    strategy:
      fail-fast: false
      matrix:
        sandbox: [CIBUILD1, CIBUILD2]
    runs-on: ubuntu-latest
    environment: ${{matrix.sandbox}}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Salesforce DX
        run: npm install --location=global sfdx-cli@${{secrets.SFDX_CLI_VERSION}}

      - name: Start Check Only Salesforce Deployment
        id: start-sf-validate
        uses: ./.github/actions/start-salesforce-deployment
        with:
          server-key: ${{secrets.SFDX_SERVER_KEY}}
          consumer-key: ${{secrets.SFDX_CONSUMER_KEY}}
          username: ${{secrets.SFDX_USER}}
          instance-url: ${{secrets.SFDX_INSTANCE_URL}}

      - name: Monitor Salesforce Deployment
        run: sfdx force:mdapi:deploy:report --targetusername buildserver --jobid ${{steps.start-sf-validate.outputs.deployment-id}} --wait -1 --verbose

      - name: Print Validate Job ID
        run: echo ${{steps.start-sf-validate.outputs.deployment-id}}
      
        # If the deployment is canceled either manually or by a newer build being started, cancel the in progress build
      - name: Cancel Handler
        if: ${{cancelled()}}
        run: sfdx force:mdapi:deploy:cancel --targetusername buildserver --jobid ${{steps.start-sf-validate.outputs.deployment-id}} --wait 2
